-- MySQL Script generated by MySQL Workbench
-- Thu Jul 16 16:09:57 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------
-- ERP

-- -----------------------------------------------------
-- Schema erp
--
-- ERP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `erp` ;

-- -----------------------------------------------------
-- Table `erp`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`department` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '部门id，主键',
  `name` CHAR(10) NOT NULL DEFAULT '' COMMENT '部门名称',
  `pid` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级部门id',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '部门表';


-- -----------------------------------------------------
-- Table `erp`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`role` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色id',
  `name` CHAR(20) NOT NULL DEFAULT '' COMMENT '角色名称',
  `department_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_department1_idx` (`department_id` ASC))
ENGINE = MyISAM
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `erp`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，管理员id',
  `username` CHAR(10) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `mail` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '管理员邮箱',
  `real_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '电话',
  `is_lock` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '账号状态，是否被锁定。 0为正常，1为已锁定',
  `last_login` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上次登录时间',
  `role_id` SMALLINT UNSIGNED NOT NULL COMMENT '所属角色id',
  `department_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_role1_idx` (`role_id` ASC),
  INDEX `fk_admin_department1_idx` (`department_id` ASC))
ENGINE = MyISAM
COMMENT = '管理员表';


-- -----------------------------------------------------
-- Table `erp`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`attribute` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '属性id',
  `name` CHAR(20) NOT NULL DEFAULT '' COMMENT '属性名称',
  `value` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '属性值',
  `kind_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '属性类别，1为属性，2为规格',
  `key_char` CHAR(10) NOT NULL DEFAULT '' COMMENT '索引字母',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '属性表';


-- -----------------------------------------------------
-- Table `erp`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`actions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '动作功能id',
  `action` CHAR(30) NOT NULL DEFAULT '' COMMENT '功能动作名称',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '系统功能动作表';


-- -----------------------------------------------------
-- Table `erp`.`dept_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`dept_action` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` TINYINT UNSIGNED NOT NULL,
  `role_id` SMALLINT UNSIGNED NOT NULL COMMENT '角色id',
  `actions_id` INT UNSIGNED NOT NULL COMMENT '动作权限id',
  PRIMARY KEY (`id`),
  INDEX `fk_group_action_role1_idx` (`role_id` ASC),
  INDEX `fk_group_action_actions1_idx` (`actions_id` ASC),
  INDEX `fk_group_action_department1_idx` (`department_id` ASC))
ENGINE = MyISAM
COMMENT = '权限表，存储部门及角色权限';


-- -----------------------------------------------------
-- Table `erp`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`category` (
  `cid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分类id，主键',
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '分类名称',
  `pid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级分类id',
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `id_UNIQUE` (`cid` ASC))
ENGINE = MyISAM
COMMENT = '分类表';


-- -----------------------------------------------------
-- Table `erp`.`category_attr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`category_attr` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kind_id` TINYINT UNSIGNED NOT NULL COMMENT '属性类别',
  `attribute_id` INT UNSIGNED NOT NULL COMMENT '属性id',
  `category_cid` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_attr_attribute1_idx` (`attribute_id` ASC),
  INDEX `fk_category_attr_category1_idx` (`category_cid` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `erp`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，品牌id',
  `name` CHAR(20) NOT NULL DEFAULT '' COMMENT '品牌名称',
  `en_name` CHAR(50) NOT NULL DEFAULT '' COMMENT '品牌英文名称',
  `logo` CHAR(30) NOT NULL DEFAULT '' COMMENT '品牌Logo',
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `erp`.`category_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`category_brand` (
  `id` INT NOT NULL COMMENT '主键',
  `brand_id` INT UNSIGNED NOT NULL,
  `category_cid` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_brand_brand1_idx` (`brand_id` ASC),
  INDEX `fk_category_brand_category1_idx` (`category_cid` ASC))
ENGINE = MyISAM
COMMENT = '分类品牌关联表';


-- -----------------------------------------------------
-- Table `erp`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，商品id',
  `name` VARCHAR(255) NOT NULL DEFAULT '‘’' COMMENT '商品名称',
  `goods` CHAR(30) NOT NULL DEFAULT '' COMMENT '商品货号',
  `manuf_date` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '生产日期',
  `marked_price` DECIMAL(10,3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '出厂价',
  `add_date` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加日期',
  `brand_id` INT UNSIGNED NOT NULL COMMENT '品牌id',
  `category_cid` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_brand1_idx` (`brand_id` ASC),
  INDEX `fk_product_category1_idx` (`category_cid` ASC))
ENGINE = MyISAM
COMMENT = '商品主表';


-- -----------------------------------------------------
-- Table `erp`.`product_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`product_details` (
  `small` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '小图',
  `medium` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '中号图',
  `big` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '大图',
  `intro` TEXT NULL COMMENT '商品介绍',
  `product_id` INT UNSIGNED NOT NULL COMMENT '商品id',
  INDEX `fk_product_details_product1_idx` (`product_id` ASC))
ENGINE = MyISAM
COMMENT = '商品详情表';


-- -----------------------------------------------------
-- Table `erp`.`product_attr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`product_attr` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `attr_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '属性id',
  `kind_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '属性类别',
  `product_id` INT UNSIGNED NOT NULL COMMENT '商品id',
  PRIMARY KEY (`id`),
  INDEX `fk_product_attr_product1_idx` (`product_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `erp`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`warehouse` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，库房id',
  `name` CHAR(10) NOT NULL DEFAULT '' COMMENT '库房名称',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '库房详细地址',
  `manager` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '库房联系人',
  `mobile` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '库房联系人电话',
  `city_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属地址id',
  `key_id` CHAR(4) NOT NULL DEFAULT '' COMMENT '库房关键码',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
COMMENT = '库房表';


-- -----------------------------------------------------
-- Table `erp`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`supplier` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键，供应商id',
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '供应商名称',
  `manager` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '联系人',
  `mobile` VARCHAR(255) NULL DEFAULT '' COMMENT '联系电话',
  `qq` VARCHAR(45) NOT NULL DEFAULT '' COMMENT 'QQ号',
  `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '电子邮箱',
  `kind_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '经营类别，1为综合，2为自由品牌',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
COMMENT = '供应商表';


-- -----------------------------------------------------
-- Table `erp`.`supplier_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`supplier_brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_id` INT UNSIGNED NOT NULL,
  `supplier_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_brand_brand1_idx` (`brand_id` ASC),
  INDEX `fk_supplier_brand_supplier1_idx` (`supplier_id` ASC))
ENGINE = MyISAM
COMMENT = '供应商品牌表';


-- -----------------------------------------------------
-- Table `erp`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`purchase_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchase_id` CHAR(13) NOT NULL DEFAULT '' COMMENT '采购单号',
  `supplier_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '供应商id',
  `warehouse_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '库房id',
  `sale_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '销售方式',
  `num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '采购数量',
  `add_date` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '采购日期',
  `expect_date` CHAR(8) NOT NULL DEFAULT '' COMMENT '预计到货时间',
  `note` VARCHAR(255) NULL DEFAULT '' COMMENT '备注',
  `purchase_status` TINYINT NULL COMMENT '采购单状态 1为采购中，2为已到货，3为部分入库，4为全部入库，5为需退回，6为退回中，7为采购关闭',
  `lock_status` TINYINT NULL COMMENT '锁定状态，0为正常，1为已锁定',
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_supplier1_idx` (`supplier_id` ASC),
  INDEX `fk_purchase_warehouse1_idx` (`warehouse_id` ASC))
ENGINE = MyISAM
COMMENT = '采购单';


-- -----------------------------------------------------
-- Table `erp`.`sku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`sku` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `goods` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '货号',
  `size` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '尺码',
  `bar_code` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '条形码',
  `add_date` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  `update_date` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后更新时间',
  `admin_name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '操作人',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = 'sku表';


-- -----------------------------------------------------
-- Table `erp`.`purchase_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`purchase_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `purchase_id` INT UNSIGNED NOT NULL COMMENT '采购单号',
  `product_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商品id',
  `sku_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `goods` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '商品货号',
  `size` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '尺码',
  `bar_code` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '商品条形码',
  `num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '数量',
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_product_purchase_order1_idx` (`purchase_id` ASC),
  INDEX `fk_purchase_product_sku1_idx` (`sku_id` ASC),
  UNIQUE INDEX `purchase_id_UNIQUE` (`purchase_id` ASC))
ENGINE = MyISAM
COMMENT = '采购商品表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
